import type { Config } from "tailwindcss";
import forms from "@tailwindcss/forms";
import containerQueries from "@tailwindcss/container-queries";

const fontStack = ["var(--font-ibm-plex-arabic)", "sans-serif"];

const config: Config = {
  darkMode: "class",
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-variant": "#e2e2e2",
        "surface-container-highest": "#e2e2e2",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#7a2f15",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#eeeeee",
        "secondary-container": "#e2dfde",
        "tertiary-fixed": "#e2e2e2",
        tertiary: "#5d5f5f",
        "primary-fixed": "#ffdbd0",
        "inverse-surface": "#2f3131",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-surface": "#1a1c1c",
        "outline-variant": "#dbc1b9",
        "on-secondary-fixed-variant": "#474746",
        "surface-tint": "#99462a",
        primary: "#99462a",
        "on-tertiary-fixed": "#1a1c1c",
        error: "#ba1a1a",
        "surface-container-high": "#e8e8e8",
        "on-primary": "#ffffff",
        "inverse-on-surface": "#f1f1f1",
        surface: "#f9f9f9",
        "on-error-container": "#93000a",
        outline: "#88726c",
        "on-primary-fixed": "#390b00",
        "secondary-fixed-dim": "#c8c6c5",
        "secondary-fixed": "#e5e2e1",
        "inverse-primary": "#ffb59e",
        "on-background": "#1a1c1c",
        "on-primary-container": "#541400",
        "tertiary-container": "#919292",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#c6c6c7",
        "primary-fixed-dim": "#ffb59e",
        "on-tertiary-container": "#292b2c",
        "surface-container-low": "#f3f3f3",
        "on-tertiary-fixed-variant": "#454747",
        "on-surface-variant": "#55433d",
        background: "#f9f9f9",
        "on-secondary-fixed": "#1c1b1b",
        "surface-bright": "#f9f9f9",
        secondary: "#5f5e5e",
        "surface-dim": "#dadada",
        "primary-container": "#d97757",
        "on-secondary-container": "#636262",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-desktop": "40px",
        gutter: "24px",
        unit: "8px",
        "container-max": "1280px",
        "margin-mobile": "16px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      fontFamily: {
        sans: fontStack,
        logo: ["var(--font-space-grotesk)", "sans-serif"],
        "display-lg": fontStack,
        "headline-lg": fontStack,
        "headline-lg-mobile": fontStack,
        "headline-md": fontStack,
        "body-lg": fontStack,
        "body-md": fontStack,
        "label-md": fontStack,
        "label-sm": fontStack,
      },
      fontSize: {
        "display-lg": [
          "48px",
          { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "display-lg-mobile": [
          "32px",
          { lineHeight: "1.15", letterSpacing: "-0.01em", fontWeight: "700" },
        ],
        "headline-lg": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-lg-mobile": ["28px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-md": [
          "14px",
          { lineHeight: "1.4", letterSpacing: "0.05em", fontWeight: "500" },
        ],
        "label-sm": ["12px", { lineHeight: "1.4", fontWeight: "500" }],
      },
    },
  },
  plugins: [forms, containerQueries],
};

export default config;
